name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before building and deploying
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' # Only run on push to master

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
        image: mahmoudnabil133/github_actions
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh 
        ssh-keyscan -H 20.21.146.3 >> ~/.ssh/known_hosts

    - name: Save the private key to a file
      run: |
        echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem

    - name: Deploy to server
      run: |
          echo "docker pull mahmoudnabil133/github_actions:latest" > deploy.sh
          # Check if the container exists before stopping and removing it
          echo "docker ps -q -f name=my-app && docker stop my-app || true" >> deploy.sh
          echo "docker ps -a -q -f name=my-app && docker rm my-app || true" >> deploy.sh
          echo "docker run -d --name my-app -p 4000:3000 mahmoudnabil133/github_actions:latest" >> deploy.sh
          chmod +x deploy.sh
          ssh -i ssh_key.pem mahmoudnabil@20.21.146.3 'bash -s' < deploy.sh
      env:
        SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}